# Generated by Django 5.1.4 on 2025-02-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, help_text='Provide an external image URL if not uploading a file.', null=True),
        ),
    ]
